# Dependencies
markdown:            kramdown
#highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
defaults:
  -
    scope:
      path:
      type: pages
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      type: posts
    values:
      permalink: /:year/:month/:day/:title.html

# Setup
title:  Neil Millard Blog
tagline: DevOps author and speaker.
description: > # this means to ignore newlines until "baseurl:"
  Neil Millard, speaker, business owner, author and DevOps specialist.
   Make work fun. Make life fun.
baseurl:  "" # the subpath of your site, e.g. /blog
url:      "https://www.neilmillard.com" # the base hostname & protocol for your site, e.g. https://example.com
paginate: 5
paginate_path: "/blog/page:num/index.html"

#About/contact
author:
  name:   Neil Millard
  email:  neil@neilmillard.com
  twitter: neil_millard
  github:  neilmillard

# Build settings
timezone: Etc/UTC
future: false

exclude: ["Gemfile", "Gemfile.lock", "LICENSE", "README.md", "CNAME", "README.md", "vendor"]

# Custom vars
version:  1.1.0

# plugins (old Gems)
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
