# Dependencies
markdown:            kramdown
#highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           :year/:month/:day/:title/

# Setup
title:  Neil Millard and Mitese Blog
tagline: Devops and cloud, simplified
description: > # this means to ignore newlines until "baseurl:"
  Mitese is a Devops, puppet and AWS specialist that can help you migrate and
   manage your application in the cloud.
baseurl:  "" # the subpath of your site, e.g. /blog
url:      "http://blog.mitese.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
paginate: 10

#About/contact
author:
  name:   Neil Millard
  email:  team@mitese.co.uk
  twitter: neil_millard
  github:  neilmillard

# Build settings
markdown: kramdown
timezone: Etc/UTC
# set the encoding to utf-8
encoding: utf-8

exclude: ["Gemfile", "Gemfile.lock", "LICENSE", "README.md", "CNAME", "README.md", "vendor"]

# Custom vars
version:  1.0.0

# Gems
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
