# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Neil Millard and Mitese Blog
email: team@mitese.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Mitese is a Devops, puppet and AWS specialist that can help you migrate and
   manage your application in the cloud.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.mitese.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: neil_millard
github_username:  neilmillard

# Build settings
markdown: kramdown
timezone: Etc/UTC
theme: minima
gems:
  - jekyll-feed


navigation:
  - title: About
    url: /about/
  - title: Contact
    url: /contact/
  - title: Mitese Group
    external_url: http://www.mitese.co.uk

exclude: ["Gemfile", "Gemfile.lock", "LICENSE", "README.md", "CNAME", "README.md", "vendor"]
