# Dependencies
markdown:            kramdown
#highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           :year/:month/:day/:title/

# Setup
title:  Neil Millard Blog
tagline: Make life and work, FUN
description: > # this means to ignore newlines until "baseurl:"
  Neil Millard, speaker, business owner and DevOps specialist.
   Make work fun. Make life fun.
baseurl:  "" # the subpath of your site, e.g. /blog
url:      "http://www.neilmillard.com" # the base hostname & protocol for your site, e.g. http://example.com
paginate: 5
paginate_path: "/blog/page:num/"

#About/contact
author:
  name:   Neil Millard
  email:  neil@neilmillard.com
  twitter: neil_millard
  github:  neilmillard

# Build settings
markdown: kramdown
timezone: Etc/UTC
future: false

exclude: ["Gemfile", "Gemfile.lock", "LICENSE", "README.md", "CNAME", "README.md", "vendor"]

# Custom vars
version:  1.0.0

# Gems
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-crosspost-to-medium

# this will disable for local testing
jekyll-crosspost_to_medium:
  enabled: false
