version: 0.1

environment_variables:
  plaintext:
    CNAME: "blog.mitese.co.uk"
    LC_ALL: C.UTF-8
    ENV LANG: en_US.UTF-8
    ENV LANGUAGE: en_US.UTF-8
    BUCKET: "logs.mitese.elb"
phases:
  install:
    commands:
      - bundle install
      - wget -O stout -q https://github.com/EagerIO/Stout/releases/download/v1.3.0/stout-linux
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - jekyll build
  post_build:
    commands:
      - bundle exec htmlproofer ./_site --allow-hash-href --check-html --disable-external
      - # ./stout deploy --env live --bucket ${BUCKET} --key $AWS_KEY --secret $AWS_SECRET --region EU-WEST-1 --root ./_site
artifacts:
  files:
    - _site/*
  discard-paths: yes
