version: 0.1

environment_variables:
  plaintext:
    CNAME: "blog.mitese.co.uk"
    LC_ALL: C.UTF-8
    ENV LANG: en_US.UTF-8
    ENV LANGUAGE: en_US.UTF-8
    BUCKET: "logs.mitese.elb"
phases:
  install:
    commands:
      - bundle install
      - sudo apt-get install s3cmd
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - jekyll build
  post_build:
    commands:
      - bundle exec htmlproofer ./_site --allow-hash-href --check-html --disable-external
      - s3cmd sync --dry-run --delete-removed ./_site/ s3://${BUCKET}/
artifacts:
  files:
    - _site/*
  discard-paths: yes
