version: 0.1

environment_variables:
  plaintext:
    CNAME: "www.neilmillard.com"
    LC_ALL: C.UTF-8
    ENV LANG: en_US.UTF-8
    ENV LANGUAGE: en_US.UTF-8
    BUCKET: "www.neilmillard.com"
phases:
  install:
    commands:
      - bundle install
      - wget -O stout -q https://github.com/EagerIO/Stout/releases/download/v1.3.0/stout-linux
      - chmod +x ./stout
  pre_build:
    commands:
      - echo Lets upgrade rubygems
      - gem update --system
  build:
    commands:
      - bundle exec jekyll build
  post_build:
    commands:
      - bundle exec htmlproofer ./_site --disable-external=true
      - ./stout deploy --bucket ${BUCKET} --key $AWS_KEY --secret $AWS_SECRET --region eu-west-1 --root ./_site
artifacts:
  files:
    - _site/*
  discard-paths: yes
